name = "Timezones"
description = "Include this file in a calendar if you need one of these timezones"

# You can check what Google Calendars outputs in an ICS file when a calendar has
# an event in a given timezone to check what to put here. Look for `BEGIN:VTIMEZONE`.

[[timezones]]
name = "America/Los_Angeles"

[timezones.standard]
name = "PST"
start = "1970-11-01T02:00:00.00"
rule = { frequency = "yearly", by_month = [11], by_day = [ { day = "sunday", num = 1 } ] }
from = "-0700"
to = "-0800"

[timezones.daylight]
name = "PDT"
start = "1970-03-08T02:00:00.00"
from = "-0800"
to = "-0700"
rule = { frequency = "yearly", by_month = [3], by_day = [ { day = "sunday", num = 2 } ] }

[[timezones]]
name = "America/New_York"

[timezones.standard]
name = "EST"
start = "1970-11-01T02:00:00.00"
rule = { frequency = "yearly", by_month = [11], by_day = [ { day = "sunday", num = 1 } ] }
from = "-0400"
to = "-0500"

[timezones.daylight]
name = "EDT"
start = "1970-03-08T02:00:00.00"
from = "-0500"
to = "-0400"
rule = { frequency = "yearly", by_month = [3], by_day = [ { day = "sunday", num = 2 } ] }

[[timezones]]
name = "Europe/Amsterdam"

[timezones.standard]
name = "CET"
start = "1970-10-25T03:00:00.00"
rule = { frequency = "yearly", by_month = [10], by_day = [ { day = "sunday", num = -1 } ] }
from = "+0200"
to = "+0100"

[timezones.daylight]
name = "CEST"
start = "1970-03-29T02:00:00.00"
from = "+0100"
to = "+0200"
rule = { frequency = "yearly", by_month = [3], by_day = [ { day = "sunday", num = -1 } ] }

[[timezones]]
name = "Europe/Paris"

[timezones.standard]
name = "CET"
start = "1970-10-25T03:00:00.00"
rule = { frequency = "yearly", by_month = [10], by_day = [ { day = "sunday", num = -1 } ] }
from = "+0200"
to = "+0100"

[timezones.daylight]
name = "CEST"
start = "1970-03-29T02:00:00.00"
from = "+0100"
to = "+0200"
rule = { frequency = "yearly", by_month = [3], by_day = [ { day = "sunday", num = -1 } ] }
