name = "Rust Compiler Team"
description = "Meetings for the compiler team"

[meta]
includes = [ "_timezones.toml" ]

[[events]]
uid = "1704469565198"
title = "Compiler Team Triage Meeting"
description = "Weekly team meeting to discuss backports and nominated issues"
location = "#t-compiler/meetings on Zulip (https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/)"
last_modified_on = "2024-03-14T15:46:00.00Z"
start = { date = "2024-01-11T10:00:00.00", timezone = "America/New_York" }
end = { date = "2024-01-11T11:00:00.00", timezone = "America/New_York" }
status = "confirmed"
organizer = { name = "t-compiler", email = "compiler@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly" } ]

[[events]]
uid = "1705072206827"
title = "steering: P-high Issue Review"
description = "Continue going over our P-high tagged issues"
location = "#t-compiler/meetings on Zulip (https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/)"
last_modified_on = "2024-03-14T15:46:00.00Z"
start = { date = "2024-01-19T10:00:00.00", timezone = "America/New_York" }
end = { date = "2024-01-19T11:00:00.00", timezone = "America/New_York" }
status = "confirmed"
organizer = { name = "t-compiler", email = "compiler@rust-lang.org" }

[[events]]
uid = "1705072461969"
title = "steering: Tracking Issue Review"
description = "Continue going over our tracking issues to update status"
location = "#t-compiler/meetings on Zulip (https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/)"
last_modified_on = "2024-03-14T15:46:00.00Z"
start = { date = "2024-01-26T10:00:00.00", timezone = "America/New_York" }
end = { date = "2024-01-26T11:00:00.00", timezone = "America/New_York" }
status = "confirmed"
organizer = { name = "t-compiler", email = "compiler@rust-lang.org" }

[[events]]
uid = "1716514360043"
title = "steering: Planning Meeting"
description = "Plan upcoming design meetings"
location = "#t-compiler/meetings on Zulip (https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/)"
last_modified_on = "2024-05-23T20:00:00.00Z"
start = { date = "2024-05-24T10:00:00.00", timezone = "America/New_York" }
end = { date = "2024-05-24T11:00:00.00", timezone = "America/New_York" }
status = "confirmed"
organizer = { name = "t-compiler", email = "compiler@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly", interval = 6 } ]
