name = "Rust Infrastructure Team"
description = "Meetings for the infrastructure team"

[meta]
includes = [ "_timezones.toml" ]

[[events]]
uid = "1704803011896"
title = "Rust Infrastructure Team Meeting"
description = "Weekly team meeting of the infrastructure team"
location = "#t-infra on Zulip (https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra)"
last_modified_on = "2025-11-13T15:30:00Z"
# Really, we use Europe/Rome, but this is close enough
start = { date = "2025-11-17T15:30:00", timezone = "Europe/Amsterdam" }
end = { date = "2025-11-17T16:00:00", timezone = "Europe/Amsterdam" }
organizer = { name = "t-infra", email = "infra@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly" } ]

[[events]]
uid = "1736255557911"
title = "rustc-perf improvements goal sync"
description = "Bi-weekly sync meeting with stakeholders of rustc-perf improvements goal in 2025H1"
location = "Zoom, ask davidtwco for link"
last_modified_on = "2025-01-07T13:13:13.13Z"
start = { date = "2025-01-15T09:15:00.00", timezone = "Europe/London" }
end = { date = "2025-01-15T09:45:00.00", timezone = "Europe/London" }
organizer = { name = "davidtwco", email = "david.wood2@arm.com" }
recurrence_rules = [ { frequency = "weekly", interval = 2, count = 13 } ]
