name = "Rust Library Team"
description = "Meetings for the library team and its working groups"

[meta]
includes = [ "_timezones.toml" ]

[[events]]
uid = "1704817069485"
title = "Libs Meeting"
description = "Weekly t-libs meeting"
location = "#t-libs/meetings on Zulip (https://rust-lang.zulipchat.com/#narrow/stream/259402-t-libs.2Fmeetings)"
last_modified_on = "2024-02-21T16:03:10.56Z"
start = { date = "2024-01-10T09:00:00.00", timezone = "US/Pacific" }
end = { date = "2024-01-10T10:00:00.00", timezone = "US/Pacific" }
status = "confirmed"
organizer = { name = "t-libs", email = "libs@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly" } ]

[[events]]
uid = "1704816854336"
title = "Libs API Meeting"
description = "Weekly t-libs-api meeting"
location = "#t-libs/meetings on Zulip (https://rust-lang.zulipchat.com/#narrow/stream/259402-t-libs.2Fmeetings)"
last_modified_on = "2024-01-09T16:15:00.00Z"
start = { date = "2024-01-09T08:00:00.00", timezone = "US/Pacific" }
end = { date = "2024-01-09T09:00:00.00", timezone = "US/Pacific" }
status = "confirmed"
organizer = { name = "t-libs-api", email = "libs@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly" } ]

[[events]]
uid = "1704817148560"
title = "Libs API Meeting - ACP Processing"
description = "Biweekly t-libs-api meeting to process ACPs"
location = "#t-libs/meetings on Zulip (https://rust-lang.zulipchat.com/#narrow/stream/259402-t-libs.2Fmeetings)"
last_modified_on = "2024-01-09T16:19:00.00Z"
start = { date = "2024-01-09T09:00:00.00", timezone = "US/Pacific" }
end = { date = "2024-01-09T10:00:00.00", timezone = "US/Pacific" }
status = "confirmed"
organizer = { name = "t-libs-api", email = "libs@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly", interval = 2 } ]
