name = "rust-analyzer Team"
description = "Meetings for the rust-analyzer team"

[[events]]
uid = "1704471430741"
title = "t-rust-analyzer Steering Meeting"
description = "Steering meeting of the rust-analyzer team"
location = "#t-compiler/rust-analyzer on Zulip (https://rust-lang.zulipchat.com/#narrow/channel/185405-t-compiler.2Frust-analyzer/topic/Steering.20meeting)"
last_modified_on = "2024-10-31T9:14:00.00Z"
start = "2024-11-05T14:00:00.00Z"
end = "2024-11-05T15:00:00.00Z"
status = "confirmed"
organizer = { name = "t-rust-analyzer", email = "compiler@rust-lang.org" }
recurrence_rules = [ { frequency = "weekly", interval = 6 } ]
